shallow_clone: true

os:
  - Visual Studio 2015

platform: x64
  - x64

branches:
  only:
    - master

install:
  - set PATH=C:\Program Files\CMake\bin;%PATH%

build:
  verbosity: detailed

configuration:
  - Debug
  
environment:
  matrix:
    - env_arch: "x64"
    - env_arch: "x86"
  
build_script:
  - mkdir build
  - cd build
  - if [%env_arch%]==[x64] (
      cmake .. -A x64 )
  - if [%env_arch%]==[x86] (
      cmake .. )
  - cmake --build .
  - cd ..

test_script:
  - mkdir "C:\tests"
  - cd build
  - cp "tests\\Debug\tests.exe" "C:\tests\tests.exe"
  - cp "tests\test_case1\Debug\test_case1.exe" "C:\tests\test_case1.exe"
  - cp "..\tests\test_case3\bin\test_case3_32.exe" "C:\tests\test_case3_32.exe"
  - cp "..\tests\test_case3\bin\test_case3_64.exe" "C:\tests\test_case3_64.exe"
  - cp "tests\test_case4\Debug\test_case4.exe" "C:\tests\test_case4.exe"
  - cp "tests\test_case5\Debug\test_case5_exe.exe" "C:\tests\test_case5_exe.exe"
  - cp "tests\test_case5\test_case5_dll\Debug\test_case5_dll.dll" "C:\tests\test_case5_dll.dll"
  - dir "C:\tests"
  - if [%env_arch%]==[x64] (
      cp "..\tests\test_case2\payload.dll" "C:\tests\payload.dll" )
  - ctest -V
  
